- name: Docker + Firewall
  hosts: all # <REPLACE WITH YOUR SPECIFY ANSIBLE HOST>
  become: true
  gather_facts: false

  tasks:
    - name: Install Docker using Rancher
      shell: curl https://releases.rancher.com/install-docker/23.0.6.sh | sudo bash -
      args:
        creates: /usr/bin/docker

    - name: Enable and start Docker service
      service:
        name: docker
        enabled: true
        state: started

    - name: Check Docker version
      shell: sudo docker version

    - name: Add user to the docker group
      user:
        name: rke
        groups: docker
        append: true

    - name: Check user details
      command: id rke
        
    - name: Allow specified TCP ports in UFW
      ufw:
        rule: allow
        port: '{{ item }}'
        proto: tcp
      loop:
        - 22
        - 80
        - 443
        - 179
        - 5473
        - 6443
        - 8472
        - 2376
        - 8472
        - "2379:2380"
        - 9099
        - 10250
        - 10251
        - 10252
        - 10254
        - "30000:32767"

    - name: Allow specified UDP ports in UFW
      ufw:
        rule: allow
        port: '{{ item }}'
        proto: udp
      loop:
        - 8285
        - 8472
        - 4789
        - "30000:32767"

    - name: Enable and reload UFW
      command: |
        sudo ufw enable
        sudo ufw reload

    - name: Update SSH configuration for TCP forwarding
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "AllowTcpForwarding yes"
        regexp: "^.*AllowTcpForwarding .*"
        state: present

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted

    - name: Check SSH service status
      service_facts:
        filters:
          name: sshd
      register: sshd_status

    - name: Display SSH service status
      debug:
        var: sshd_status
