- name: Uninstall Docker
  hosts: all
  become: true
  tasks:
    - name: Stop Docker service
      service:
        name: docker
        state: stopped
      tags: docker

    - name: Uninstall Docker packages
      apt:
        name:
          - containerd.io
          - docker-ce
          - docker-ce-cli
        state: absent
      tags: docker